### ISSUE TITLE
raise ruleset xxx already exist error when multithreading is used

### ISSUE THREAD

**Issue by MofiU** [ulfurinn/wongi-engine#69]
```ruby
require 'wongi-engine'
class MyEngine
   include Wongi::Engine::DSL
   def initialize
      @engine = Wongi::Engine.create
      m_ruleset  = ruleset 'test' do 
         rule 'friend' do
           forall{
             has :A, :friend, :B
           }
         end
      end
      @engine << m_ruleset 
   end

   def add_fact(fact)
     @engine << fact
   end
end 

10.times do 
   t = Thread.new do
     p 'new thread'
     MyEngine.new.add_fact(["Alice", :friend, "Bob"])
   end
   t.join
end
```

Get error 
`
gems/wongi-engine-0.3.3/lib/wongi-engine/ruleset.rb:13:in `register': ruleset test already exists (Wongi::Engine::Error)
`
I want to create a new engine dynamic by database and how can i fix it.

**Comment by renyijiu** [comment]
I have the same problem. 

I found the `rulesets defined in the Wongi::EngineRuleset` method use the class instance variable and it will check the ruleset before register. if the ruleset exist, it will raise an error.

So my temporary solution is check the ruleset manually before use the `<<` method.

```ruby
engine << my_ruleset unless Wongi::Engine::Ruleset.rulesets.keys.include?(my_ruleset_name)
```

**Comment by ulfurinn** [comment]
All of this is by design.

The ruleset in your example has no instance-specific data, so there's no point in creating a new one every time. Create it once and install it in different engine instances. The named registry is supposed to be global.

If your actual ruleset does contain instance-specific data, either generate random names or don't use names at all if you're never going to reuse them.
